#import "../../Explore/queries/articleFields.gql"
#import "./heroFields.gql"

query Article($slug: ID!) {
  caseStudy(id: $slug) {
    id
    ...HeroFields
    editorUrl
    isFavorited
    sections {
      id
      type
      contents {
        id
        ... on Heading {
          size
          text
        }
        ... on Paragraph {
          text
        }
        ... on Results {
          results
        }
        ... on Images {
          images {
            id
            url
          }
        }
      }
    }
    similar {
      ...ArticleFields
      industries {
        id
        industry {
          id
          name
        }
      }
    }
    review {
      id
      name
      comment
      companyName
      avatar
    }
  }
}
