// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DatePickerController from "./date_picker_controller"
application.register("date-picker", DatePickerController)

import InlineEditingController from "./inline_editing_controller"
application.register("inline-editing", InlineEditingController)

import MenuController from "./menu_controller"
application.register("menu", MenuController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import TextareaController from "./textarea_controller"
application.register("textarea", TextareaController)
