query Availability {
  viewer {
    ... on User {
      id
      availability
      interviews {
        id
        startsAt
        specialist {
          id
          firstName
        }
      }
    }
  }
}
