query OnboardingData($isFreelancer: Boolean!) {
  currentCompany @skip(if: $isFreelancer) {
    id
    name
    kind
    intent
    audience
    businessType
  }
  interests {
    id
    term
  }
  industries {
    id
    name
  }
}
