#import "../../Feed/queries/articleFields.gql"

query Article($slug: ID!) {
  caseStudy(id: $slug) {
    id
    title
    subtitle
    editorUrl
    companyType
    comment
    skills {
      id
      primary
      skill {
        id
        name
      }
    }
    company {
      id
      name
      logo
      favicon
      businessType
      website
    }
    specialist {
      id
      bio
      avatar
      name
      firstName
      profilePath
      unavailableUntil
      location
      consultation {
        id
        status
        interview {
          id
          status
          startsAt
        }
      }
      conversation {
        id
      }
      account {
        id
        timezone
      }
    }
    sections {
      id
      type
      contents {
        id
        ... on Heading {
          size
          text
        }
        ... on Paragraph {
          text
        }
        ... on Results {
          results
        }
        ... on Images {
          images {
            id
            url
          }
        }
      }
    }
    similar {
      ...ArticleFields
    }
  }
}
