fragment AgreementFields on Agreement {
  id
  status
  invoicing
  hourlyRate
  collaboration
  specialist {
    id
    name
    firstName
  }
  user {
    id
    name
    firstName
  }
  company {
    id
    name
  }
}
