#import "./messageFields.gql"

query ConversationMessages($id: ID!, $cursor: String) {
  conversation(id: $id) {
    id
    unreadCount
    messages(last: 50, before: $cursor) {
      pageInfo {
        hasPreviousPage
        startCursor
      }
      edges {
        node {
          ...MessageFields
        }
      }
    }
  }
}
