fragment MessageFields on MessageInterface {
  id
  content
  createdAt
  attachments {
    id
    url
    isImage
    filename
  }

  ... on GuildPostMessage {
    calendlyUrl
    post {
      id
      title
    }
    author {
      id
      name
      avatar
    }
  }

  ... on UserMessage {
    status @client
    author {
      id
      name
      avatar
    }
  }

  ... on ConsultationRequestMessage {
    consultation {
      id
      status
      interview {
        id
        status
      }
    }
    author {
      id
      name
      avatar
    }
  }

  ... on InterviewRequestMessage {
    interview {
      id
      status
      specialist {
        id
      }
    }
    author {
      id
      name
      avatar
    }
  }

  ... on InterviewDeclinedMessage {
    interview {
      id
      specialist {
        id
        firstName
      }
      user {
        id
        firstName
      }
    }
  }

  ... on InterviewAutoDeclinedMessage {
    interview {
      id
      specialist {
        id
        firstName
      }
    }
  }

  ... on AgreementCreatedMessage {
    agreement {
      id
      status
      invoicing
      hourlyRate
      collaboration
      specialist {
        id
        name
        firstName
      }
      company {
        id
        name
      }
    }
    author {
      id
      name
      avatar
    }
  }

  ... on AgreementDeclinedMessage {
    agreement {
      id
      user {
        id
        name
      }
      specialist {
        id
        firstName
      }
    }
  }

  ... on AgreementAcceptedMessage {
    agreement {
      id
      user {
        id
        name
      }
      company {
        id
        name
      }
      specialist {
        id
        firstName
      }
    }
  }

  ... on ConsultationDeclinedMessage {
    consultation {
      id
      specialist {
        id
        firstName
      }
    }
  }

  ... on InterviewScheduledMessage {
    startsAt
    interview {
      id
      status
      specialist {
        id
        firstName
      }
    }
  }
}
