fragment MessageFields on MessageInterface {
  id
  content
  createdAt
  attachments {
    id
    url
    isImage
    filename
  }

  ... on GuildPostMessage {
    calendlyUrl
    post {
      id
      title
    }
    author {
      id
      name
      avatar
    }
  }

  ... on UserMessage {
    status @client
    author {
      id
      name
      avatar
    }
  }
}
