CLIENT_CONFIG = {
  'ROLLBAR_ENV' => ENV['ROLLBAR_ENV'],
  'ROLLBAR_CLIENT_TOKEN' => ENV['ROLLBAR_CLIENT_TOKEN'],
  'STRIPE_PUBLIC_KEY' => ENV['STRIPE_PUBLIC_KEY'],
  'SENTRY_FRONTEND_DSN' => ENV['SENTRY_FRONTEND_DSN'],
  'SENTRY_ENVIRONMENT' => ENV['SENTRY_ENVIRONMENT'],
  'TALKJS' => ENV['TALKJS'],
  'INTERCOM_APP_ID' => ENV['INTERCOM_APP_ID']
}
