#import 'src/views/CaseStudyArticle/queries/heroFields.gql'

query DashboardData {
  viewer {
    ... on Specialist {
      id
      unavailableUntil
      caseStudiesCount
      reviews {
        id
      }
    }
  }
  topCaseStudies {
    ...HeroFields
    id
    path
    coverPhoto
  }
  upcomingEvents {
    id
    title
    startsAt
    host {
      id
      name
    }
    coverPhotoUrl
  }
}
