query DashboardData {
  viewer {
    ... on Specialist {
      id
      caseStudies {
        id
      }
      reviews {
        id
      }
    }
  }
  topCaseStudies {
    id
    title
    specialist {
      id
      name
      avatar
    }
    coverPhoto
  }
  upcomingEvents {
    id
    title
    startsAt
    host {
      id
      name
    }
    coverPhotoUrl
  }
}
