query DashboardData {
  viewer {
    ... on Specialist {
      caseStudies {
        id
      }
      reviews {
        id
      }
    }
  }
  collaborationRequests {
    nodes {
      id
      author {
        id
        name
        avatar
        location
      }
      title
      excerpt
    }
  }
  topCaseStudies {
    id
    title
    specialist {
      id
      name
      avatar
    }
    coverPhoto
  }
  upcomingEvents {
    id
    title
    startsAt
    host {
      id
      name
    }
    coverPhotoUrl
  }
}
