fragment ArticleFields on CaseStudyArticle {
  id
  path
  isFavorited
  skills {
    id
    primary
    skill {
      id
      name
      color
    }
  }
  industries {
    id
    industry {
      id
      name
    }
  }
}
