#import 'src/views/CaseStudyArticleNew/queries/heroFields.gql'

fragment ArticleFields on CaseStudyArticle {
  id
  ...HeroFields
  path
  isFavorited
  skills {
    id
    primary
    skill {
      id
      name
      color
    }
  }
  industries {
    id
    industry {
      id
      name
    }
  }
  specialist {
    id
    name
    avatar
    unavailableUntil
  }
  company {
    id
    name
    website
    favicon
    businessType
  }
  resultsContent {
    id
    results
  }
}
