#import "./articleFields.gql"
#import "../../CaseStudyArticleNew/queries/heroFields.gql"

query FavoritedArticles($cursor: String) {
  favoritedArticles(after: $cursor, first: 15) {
    pageInfo {
      endCursor
      hasNextPage
    }
    edges {
      node {
        ...ArticleFields
        ...HeroFields
      }
    }
  }
}
