#import "./articleFields.gql"

query Feed($cursor: String) {
  interests {
    id
    term
  }
  feed(after: $cursor, first: 15) {
    pageInfo {
      endCursor
      hasNextPage
    }
    edges {
      node {
        id
        interest {
          id
          term
        }
        article {
          ...ArticleFields
        }
      }
    }
  }
}
