const INTERESTS = [
  "Scale Performance Marketing",
  "Creative PR Strategy",
  "Long-Form Content Marketing",
  "Start B2B Podcast",
  "Improve SEO Rankings",
  "Creative Growth Marketing",
  "Develop Value Proposition",
  "Build SEO Strategy",
  "Enter German Market",
  "Test Instagram Ads",
  "Create Newsletter",
  "Create Video Content",
  "Paid Acquisition Strategy",
  "Enter Middle-Eastern Market",
  "Build Trade Show Strategy",
  "Implement Hubspot",
  "UX Optimisation",
  "Rebranding Strategy",
  "Research Target Market",
  "Improve Content Design",
  "Create Brand Identity",
  "Build Marketing Strategy",
  "B2B Ghostwriting",
  "Growth Marketing",
  "Improve Funnel Conversion Rate",
  "Redesign Website",
  "Design Paid Marketing Assets",
  "Run Webinars",
  "Launch App Ad Campaigns",
  "Improve Online Reputation",
  "Build Online Community",
  "Content Marketing Strategy",
  "Funny Social Media Content",
  "Improve User Acquisition Profitability",
  "Update Strategic Messaging",
  "Social Media Advertising",
  "Research Landing Page Usability",
  "Virtual Event Strategy",
  "App Store Optimisation",
  "Creative Design",
  "Hubspot & Salesforce Integration",
  "Create Explainer Video",
  "Create Webflow Website",
  "Paid Marketing Strategy",
  "Data-Driven Content",
  "Outbound Email Campaigns",
  "Rewrite Web Copy",
  "Launch in German Market",
  "Rebuild Marketing Automation",
  "User Research",
];

export default INTERESTS;
