#import "./paymentRequestFields.gql"

mutation ApprovePaymentRequest($input: ApprovePaymentRequestInput!) {
  approvePaymentRequest(input: $input) {
    paymentRequest {
      ...PaymentRequestFields
    }
  }
}
