mutation ApprovePaymentRequest($input: ApprovePaymentRequestInput!) {
  approvePaymentRequest(input: $input) {
    paymentRequest {
      id
      status
      payment {
        id
        status
      }
    }
  }
}
