#import "./paymentRequestFields.gql"

mutation CancelPaymentRequest($input: CancelPaymentRequestInput!) {
  cancelPaymentRequest(input: $input) {
    paymentRequest {
      ...PaymentRequestFields
    }
  }
}
