#import "./paymentRequestFields.gql"

mutation CreatePaymentRequest($input: CreatePaymentRequestInput!) {
  createPaymentRequest(input: $input) {
    paymentRequest {
      ...PaymentRequestFields
      company {
        id
        name
      }
    }
  }
}
