#import "./paymentRequestFields.gql"

mutation DisputePaymentRequest($input: DisputePaymentRequestInput!) {
  disputePaymentRequest(input: $input) {
    paymentRequest {
      ...PaymentRequestFields
    }
  }
}
