query FreelancerPaymentRequests($cursor: String) {
  paymentRequests(after: $cursor, first: 20) {
    pageInfo {
      endCursor
      hasNextPage
    }
    edges {
      node {
        id
        status
        pastDue
        amount
        createdAt
        lineItems {
          amount
          description
        }
        company {
          id
          name
        }
      }
    }
  }
}
