#import "./paymentRequestFields.gql"

query FreelancerPaymentRequests($cursor: String) {
  paymentRequests(after: $cursor, first: 20) {
    pageInfo {
      endCursor
      hasNextPage
    }
    edges {
      node {
        ...PaymentRequestFields
        company {
          id
          name
        }
      }
    }
  }
}
