query FreelancerPaymentRequest($id: ID!) {
  paymentRequest(id: $id) {
    id
    status
    amount
    company {
      id
      name
    }
    specialist {
      id
      name
    }
    payment {
      id
      status
      paymentMethod
      paymentIntent {
        secret
      }
    }
    lineItems {
      amount
      description
    }
  }
}
