fragment PaymentRequestFields on PaymentRequest {
  id
  status
  amount
  createdAt
  dueAt
  lineItems {
    amount
    description
  }
  company {
    id
    name
  }
  specialist {
    id
    name
  }
}
