fragment SpecialistFields on Specialist {
  id
  name
  firstName
  avatar
  coverPhoto
  location
  bio
  linkedin
  website
  city
  guild
  country {
    id
  }

  caseStudies {
    id
    companyType
    title
    coverPhoto
    company {
      favicon
    }
    skills {
      skill {
        id
        name
      }
    }
  }

  reviews {
    id
    name
    role
    comment
    companyName
    avatar
  }
}
