#import '../../Messages/queries/agreementFields.gql'

mutation CreateAgreement($input: CreateAgreementInput!) {
  createAgreement(input: $input) {
    conversation {
      id
      agreement {
        ...AgreementFields
      }
    }
  }
}
