query Article($articleId: ID!) {
  caseStudy(id: $articleId) {
    id
    title
    subtitle
    skills {
      id
      primary
      skill {
        id
        name
      }
    }
    company {
      id
      logo
      favicon
    }
    comment
    specialist {
      id
      bio
      avatar
      name
      firstName
      profilePath
      conversation {
        id
      }
      interview {
        id
        status
        startsAt
      }
      consultation {
        id
        status
      }
    }
    sections {
      id
      type
      contents {
        id
        ... on Heading {
          size
          text
        }
        ... on Paragraph {
          text
        }
        ... on Results {
          results
        }
        ... on Images {
          images {
            id
            url
          }
        }
      }
    }
  }
}
