fragment ArticleFields on CaseStudyArticle {
  id
  title
  comment
  skills {
    id
    primary
    skill {
      id
      name
    }
  }
  specialist {
    id
    name
    firstName
    avatar
    conversation {
      id
    }
    consultation {
      id
      status
      interview {
        id
        status
        startsAt
      }
    }
  }
}
