query CaseStudySearchFormDetails($id: ID!) {
  caseStudySearch(id: $id) {
    id
    name
    goals
    preferences
    isFinalized
    skills {
      id
      skill {
        id
        name
      }
    }
  }
}
