query CategoryQrticles($slug: String!, $after: String) {
  skillCategory(slug: $slug) {
    id
    articles(first: 8, after: $after) {
      pageInfo {
        endCursor
        hasNextPage
      }
      edges {
        node {
          id
          title
          comment
          company {
            id
            favicon
          }
          specialist {
            id
            avatar
            name
          }
          skills {
            id
            skill {
              id
              name
            }
          }
        }
      }
    }
  }
}
