#import "./articleFields.gql"

mutation finalizeCaseStudySearch($input: FinalizeCaseStudySearchInput!) {
  finalizeCaseStudySearch(input: $input) {
    search {
      id
      isFinalized
      preferences
      results(first: 12) {
        nodes {
          ...ArticleFields
        }
      }
    }
  }
}
