#import "./articleFields.gql"

query Shortlist($id: ID!) {
  currentCompany {
    id
    name
  }
  caseStudySearch(id: $id) {
    id
    name
    results(first: 5) {
      nodes {
        ...ArticleFields
      }
    }
  }
}
