query Shortlists {
  currentCompany {
    id
    kind
    industry {
      id
      name
    }
  }
  interests {
    id
    name
    results(first: 5) {
      nodes {
        id
        specialist {
          id
          name
          avatar
        }
      }
    }
  }
}
