query ExplorerArchivedArticles {
  archivedArticles {
    nodes {
      id
      title
      subtitle
      company {
        id
        logo
      }
      specialist {
        id
        name
        avatar
      }
    }
  }
}
