query archivedRecommendations($id: ID!) {
  caseStudySearch(id: $id) {
    id
    name
    archived {
      edges {
        node {
          id
          title
          subtitle
          specialist {
            id
            avatar
          }
        }
      }
    }
  }
}
