mutation createCaseStudySearch($input: CreateCaseStudySearchInput!) {
  createCaseStudySearch(input: $input) {
    search {
      id
      name
      goals
      skills {
        id
        skill {
          id
          value: name
          label: name
        }
      }
    }
  }
}
