query CreateOrEditSearch {
  currentCompany {
    id
    kind
    businessType
    industry {
      id
      name
    }
  }
  caseStudySkills {
    id
    value: name
    label: name
  }
  popularCaseStudySkills {
    id
    value: name
    label: name
  }
}
