#import "./articleFields.gql"
query getCaseStudy($id: ID!) {
  caseStudy(id: $id) {
    ...ArticleFields
    comment
    specialist {
      id
      bio
      avatar
      name
      firstName
    }
    sections {
      id
      type
      contents {
        id
        ... on Heading {
          size
          text
        }
        ... on Paragraph {
          text
        }
        ... on Results {
          results
        }
        ... on Images {
          images {
            id
            url
          }
        }
      }
    }
  }
}
