#import "./articleFields.gql"
query ExplorerSearchRecommendations($id: ID!) {
  caseStudySearch(id: $id) {
    id
    name
    companyRecomendation
    results(first: 12) {
      nodes {
        ...ArticleFields
      }
    }
  }
}
