#import "./articleFields.gql"
query ExplorerSearchRecommendations($id: ID!) {
  currentCompany {
    id
    name
  }
  caseStudySearch(id: $id) {
    id
    name
    goals
    preferences
    isFinalized
    companyRecomendation
    skills {
      id
      skill {
        id
        name
      }
    }
    results(first: 12) {
      nodes {
        ...ArticleFields
      }
    }
  }
}
