query ExplorerFavoriteArticles {
  savedArticles {
    nodes {
      id
      title
      subtitle
      company {
        id
        logo
      }
      specialist {
        id
        name
        avatar
      }
    }
  }
}
