query ExplorerSharedArticles {
  sharedArticles {
    id
    article {
      id
      title
      subtitle
      company {
        id
        logo
      }
      specialist {
        id
        name
        avatar
      }
    }
  }
}
