query ExplorerSidebar {
  caseStudySearches {
    id
    name
    isFinalized
    companyRecomendation
    results {
      nodes {
        id
      }
    }
  }
  savedArticles {
    nodes {
      id
    }
  }
}
