mutation updateCaseStudySearch($input: UpdateCaseStudySearchInput!) {
  updateCaseStudySearch(input: $input) {
    search {
      id
      goals
      skills {
        id
        skill {
          id
          value: name
          label: name
        }
      }
    }
  }
}
