fragment ArticleFields on CaseStudyArticle {
  id
  slug
  title
  subtitle
  specialist {
    id
    name
    avatar
  }
  company {
    id
    name
    favicon
  }
  firstImage {
    id
    url
  }
}
