#import "./articleFields.gql"

query Feed {
  feed {
    edges {
      node {
        id
        interest {
          id
          term
        }
        article {
          ...ArticleFields
        }
      }
    }
  }
}
