#import "./articleFields.gql"

query InterestFeed($id: ID!) {
  interest(id: $id) {
    id
    term
    articles {
      edges {
        node {
          ...ArticleFields
        }
      }
    }
  }
}
