#import "./articleFields.gql"

mutation CreateInterestSearch($input: CreateCaseStudyInterestPreviewInput!) {
  createCaseStudyInterestPreview(input: $input) {
    interestPreview {
      id
      term
      articles {
        edges {
          node {
            ...ArticleFields
          }
        }
      }
    }
  }
}
