query Notifications {
  notifications(first: 20) {
    nodes {
      __typename
      id
      createdAt
      ... on SuggestedPost {
        specialist {
          id
          name
        }
        guildPost {
          id
          title
        }
      }
    }
  }
}
