query ConversationMessages($id: ID!, $cursor: String) {
  conversation(id: $id) {
    id
    unreadMessageCount
    messages(last: 50, before: $cursor) {
      pageInfo {
        hasPreviousPage
        startCursor
      }
      edges {
        node {
          id
          content
          createdAt
          author {
            id
            name
            avatar
          }
        }
      }
    }
  }
}
