query ConversationMessages($id: ID!) {
  conversation(id: $id) {
    id
    unreadMessageCount
    messages {
      edges {
        node {
          id
          content
          createdAt
          author {
            id
            name
            avatar
          }
        }
      }
    }
  }
}
