subscription ReceivedMessage {
  receivedMessage {
    message {
      id
      content
      createdAt
      author {
        id
        name
        avatar
      }
      attachments {
        id
        url
        isImage
        filename
      }
      conversation {
        id
        unreadCount
      }
    }
  }
}
