subscription ReceivedMessage {
  receivedMessage {
    message {
      id
      content
      createdAt
      author {
        id
        name
        avatar
      }
      conversation {
        id
      }
    }
  }
}
