mutation SendMessage($input: SendMessageInput!) {
  sendMessage(input: $input) {
    message {
      id
      content
      createdAt
      status @client
      author {
        id
        name
        avatar
      }
      attachments {
        id
        url
        filename
      }
    }
  }
}
