#import "../../Explore/queries/articleFields.gql"
#import "../../CaseStudyArticleNew/queries/heroFields.gql"

query InterestPreview($term: String!, $cursor: String) {
  search(term: $term) {
    id
    term
    articles(first: 15, after: $cursor) {
      pageInfo {
        endCursor
        hasNextPage
      }
      edges {
        node {
          ...HeroFields
          ...ArticleFields
        }
      }
    }
  }
}
